spring.application.name=spring_security_backend

#JWT Configuration
#JWT Signature
spring.jwtKey=V29dsjT9pQ5T8aYxuK8GkNFrP2c7ZfLmWkDl3z3bNqE
#JWT Expiration
spring.security.jwt.jwtExpirationMs=3000000

#DB Config
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/springSecurity?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Ijse@1234

#hibernateConfig
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

